#!/bin/bash

source /etc/update-motd.d/colors.txt

#echo -e ${DEFAULT_COLOR}; toilet -d /etc/update-motd.d/ -f ivrit "XRAY"

echo
echo
echo -e " ${TITLE_COLOR}################################################################################"
echo -e " ${TITLE_COLOR}                        WARNING: AUTHORIZED ACCESS ONLY                         "
echo -e " ${TITLE_COLOR}################################################################################"
echo
echo -e " ${TITLE_COLOR}This system is for the use of authorized users only. Individuals using this     "
echo -e " ${TITLE_COLOR}computer system without authority, or in excess of their authority, are subject "
echo -e " ${TITLE_COLOR}to having all of their activities on this system monitored and recorded.        "
echo
echo -e " ${TITLE_COLOR}Any unauthorized access or use of this system is prohibited and may be subject  "
echo -e " ${TITLE_COLOR}to criminal and/or civil penalties. All activities on this system are logged    "
echo -e " ${TITLE_COLOR}and monitored. By accessing this system, you agree to comply with all applicable"
echo -e " ${TITLE_COLOR}company policies, and you consent to the monitoring and recording of your       "
echo -e " ${TITLE_COLOR}activities.                                                                     "
echo
echo -e " ${TITLE_COLOR}If you are not an authorized user, you must disconnect immediately.             "
echo
echo -e " ${TITLE_COLOR}Unauthorized access to this device is strictly prohibited and will be prosecuted"
echo -e " ${TITLE_COLOR}to the fullest extent of the law.                                               "
echo
echo -e " ${TITLE_COLOR}################################################################################"
echo
echo -e " ${TITLE_COLOR}            +----------------------------------------------------+"
echo -e " ${TITLE_COLOR}            | █████ █████ ███████████     █████████   █████ █████|"
echo -e " ${TITLE_COLOR}            |░░███ ░░███ ░░███░░░░░███   ███░░░░░███ ░░███ ░░███ |"
echo -e " ${TITLE_COLOR}            | ░░███ ███   ░███    ░███  ░███    ░███  ░░███ ███  |"
echo -e " ${TITLE_COLOR}            |  ░░█████    ░██████████   ░███████████   ░░█████   |"
echo -e " ${TITLE_COLOR}            |   ███░███   ░███░░░░░███  ░███░░░░░███    ░░███    |"
echo -e " ${TITLE_COLOR}            |  ███ ░░███  ░███    ░███  ░███    ░███     ░███    |"
echo -e " ${TITLE_COLOR}            | █████ █████ █████   █████ █████   █████    █████   |"
echo -e " ${TITLE_COLOR}            |░░░░░ ░░░░░ ░░░░░   ░░░░░ ░░░░░   ░░░░░    ░░░░░    |"
echo -e " ${TITLE_COLOR}            +----------------------------------------------------+"
echo