#!/bin/bash

source /etc/update-motd.d/colors.txt

check_service() {
    local service=$1
    if systemctl is-active --quiet "$service"; then
        echo -ne "\e[32m▲\e[0m $service | "  # Зеленая стрелка вверх (включен)
    else
        echo -ne "\e[31m▼\e[0m $service | "  # Красная стрелка вниз (выключен)
    fi
}

check_ufw() {
    if ufw status | grep -q "Status: active"; then
        echo -ne "\e[32m▲\e[0m ufw "  # Зеленая стрелка вверх (включен)
    else
        echo -ne "\e[31m▼\e[0m ufw "  # Красная стрелка вниз (выключен)
    fi
}

services=("x-ui" "nginx")
echo -ne "${TITLE_COLOR}Processes...........: ${NC}"

for service in "${services[@]}"; do
    check_service "$service"
done

check_ufw  # Последний без |
