#!/bin/bash

source /etc/update-motd.d/colors.txt

check_service() {
    local service=$1
    if systemctl is-active --quiet "$service"; then
        echo -ne "\e[32m▲\e[0m ${DEFAULT_COLOR}$service | "
    else
        echo -ne "\e[31m▼\e[0m ${DEFAULT_COLOR}$service | "
    fi
}

check_ufw() {
    if ufw status | grep -q "Status: active"; then
        echo -ne "\e[32m▲\e[0m ${DEFAULT_COLOR}ufw "
    else
        echo -ne "\e[31m▼\e[0m ${DEFAULT_COLOR}ufw "
    fi
}

services=("x-ui" "nginx")
echo -ne " ${TITLE_COLOR}Processes...........: ${NC}"

for service in "${services[@]}"; do
    check_service "$service"
done

check_ufw
